### ISSUE TITLE
events, methods and ability close by key

### ISSUE THREAD

**Issue by devmondo** [abhisack/FModal.js#3]
hi, lovely work, there, can we have ability close the modal by hitting esc key ?

also can we do the whole thing in javascript instead of using data attributes?

also can we have some events emitting like modal closed, modal opened ?

thanks in advanced.

**Comment by abhisack** [comment]
Thanks for such useful suggestions dev!
I'll be first working on first and second feature you suggested and then think over the third one.

**Comment by devmondo** [comment]
thanks man :)
 regarding usage of jquery for events, you dont need it, https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener and other vanilla js will do the job and you wont have dependencies :)
http://youmightnotneedjquery.com/

**Comment by devmondo** [comment]
i took the liberty and created a pull request :)

**Comment by abhisack** [comment]
I added esc key support but the code from your pull request isn't working. What do you think might be going wrong?

**Comment by devmondo** [comment]
hey man, i found the problem now it is corrected and you are jquery free :)

the issue was happening because with old code `openModal` was would treat `this` as the element, with new code that is no longer the case, to fix it we pass the element to `openModal()` as param.

**Comment by devmondo** [comment]
also, right now it is not convenient to define modal content in easy way, suppose i want to inject some  complex html, `data-text` is not adequate for that, i suggest taking a lead from bootstrap and how you define whole html template for modal and  you add `data-target='#modal-1` to the button that will trigger the modal.

this will make your modal really flexible for users :)
