### ISSUE TITLE
When modal is open, background scrolling is must  stopped

### ISSUE THREAD

**Issue by zoghal** [abhisack/FModal.js#6]
When modal is open, background scrolling is must  stopped

**Comment by abhisack** [comment]
Such a good suggestion! I'll make a commit as soon as I implement the feature suggested by you.
Thanks for noticing the bug

**Comment by abhisack** [comment]
It doesn't look quite nice when whole body of the page shifts right when scrollbar is being removed. I will make commit and close this issue as I find a suitable solution.

**Comment by zoghal** [comment]
ok
