### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by devmondo** [abhisack/FModal.js#7]
to be able to use this with NPM or Client side package managers like JSPM, please add `package.json` with `main` property.

**Comment by abhisack** [comment]
Added `package.json`. Now it can be installed using `npm install fmodal`. But I wasn't sure what to use for the main property.

**Comment by devmondo** [comment]
great man, you can do this
`main:'js/fmodal.js'`

did you check my pull request i fixed it to make it work now .
